name: builder
on: [pull_request]
jobs:
  builder:
    runs-on: ubuntu-18.04
    steps:
      - uses: action/checkout@v2
      - uses: action/setup-go@v2
      - uses: golangci/golangci-lint-action@v2
        name: Lint
        with:
          version: v1.37
      - name: Test
        run: go test ./...